version: '3'

services:
  pamviapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: pamvi-docker
    container_name: pamviapp
    restart: always
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pamvi
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/pamvi

  db:
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data