version: '3'

services:
  db:
    image: postgres:14.3
    container_name: ${DB_NAME}
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4:8.5
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${MANAGERDB_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${MANAGERDB_PASSWORD}
    volumes:
      - ./pgAdmin:/var/lib/pgadmin