export const EnvConfiguration = () => ({
    apiHost: process.env.API_HOST,
    apiPort: +process.env.API_PORT,
    apiProtocol: +process.env.API_PROTOCOL,
    appVersion: process.env.APP_VERSION || '0.0.1',
    corsOrigin: +process.env.CORS_ORIGIN,
    environment: process.env.NODE_ENV || 'dev',
    dbHost: process.env.DB_HOST,
    dbName: process.env.DB_NAME || 'PAMVIDB',
    dbPassword: process.env.DB_PASSWORD,
    dbPort: process.env.DB_PORT || 5432,
    dbUsername: process.env.DB_USERNAME || 'postgres',
    defaultLimit: +process.env.DEFAULT_LIMIT || 5,
    filesExtensionsImageValid: process.env.FILES_EXTENSIONS_IMAGE_VALID,
    jwtSecret: process.env.JWT_SECRET,
    mailHost: process.env.MAIL_HOST || 'smtp.gmail.com',
    mailPassword: process.env.MAIL_PASSWORD,
    mailSender: process.env.MAIL_SENDER,
    mailUser: process.env.MAIL_USER,
    managerDbEmail: process.env.MANAGERDB_EMAIL,
    managerDbPassword: process.env.MANAGERDB_PASSWORD,
    stage: process.env.STAGE || 'dev',
});