export const EnvConfiguration = () => ({
    environment: process.env.NODE_ENV || 'dev',
    dbHost: process.env.DB_HOST,
    dbName: process.env.DB_NAME || 'PAMVIDB',
    dbPassword: process.env.DB_PASSWORD,
    dbPort: process.env.DB_PORT || 5432,
    dbUsername: process.env.DB_USERNAME || 'postgres',
    defaultLimit: +process.env.DEFAULT_LIMIT || 5,
    filesExtensionsImageValid: process.env.FILES_EXTENSIONS_IMAGE_VALID,
    hostApi: process.env.HOST_API,
    jwtSecret: process.env.JWT_SECRET,
    mailHost: process.env.MAIL_HOST || 'smtp.gmail.com',
    mailPassword: process.env.MAIL_PASSWORD,
    mailSender: process.env.MAIL_SENDER,
    mailUser: process.env.MAIL_USER,
    port: +process.env.PORT,
});